import React, { useState, useEffect, useMemo } from 'react';
import { Link } from 'react-router-dom';
import Header from '../../components/ui/Header';
import Breadcrumb from '../../components/ui/Breadcrumb';
import Icon from '../../components/AppIcon';
import Button from '../../components/ui/Button';
import AlertTable from './components/AlertTable';
import AlertFilters from './components/AlertFilters';
import AlertConfiguration from './components/AlertConfiguration';
import AlertDetails from './components/AlertDetails';
import BulkActions from './components/BulkActions';
import AlertStats from './components/AlertStats';

const AlertManagement = () => {
  const [alerts, setAlerts] = useState([]);
  const [filteredAlerts, setFilteredAlerts] = useState([]);
  const [selectedAlerts, setSelectedAlerts] = useState([]);
  const [filters, setFilters] = useState({
    severity: '',
    location: '',
    status: '',
    riskType: '',
    startDate: '',
    endDate: ''
  });
  const [isConfigOpen, setIsConfigOpen] = useState(false);
  const [selectedAlert, setSelectedAlert] = useState(null);
  const [isDetailsOpen, setIsDetailsOpen] = useState(false);
  const [currentSite, setCurrentSite] = useState('Site Alpha');

  // Mock alert data
  useEffect(() => {
    const mockAlerts = [
      {
        id: 'ALT-2025-001',
        timestamp: new Date('2025-01-16T08:30:00'),
        location: 'North Pit - Zone A',
        severity: 'Critical',
        riskType: 'Rockfall',
        status: 'Active',
        description: `Critical rockfall risk detected in North Pit Zone A. AI analysis indicates 92% probability of rockfall within next 6 hours based on recent ground movement patterns, increased vibration levels, and adverse weather conditions.\n\nImmediate evacuation of personnel recommended. Emergency response protocols should be activated.`,
        riskProbability: 92,
        confidenceLevel: 87,
        affectedArea: '150m x 200m',
        sensorSource: 'Sensor Array NP-A-01',
        weather: 'Heavy Rain',
        temperature: '12°C',
        windSpeed: '25 km/h',
        rainfall: '45mm/24h',
        coordinates: { lat: -33.8688, lng: 151.2093 },
        responseHistory: [
          {
            user: 'Sarah Johnson',
            action: 'Alert Generated',
            timestamp: new Date('2025-01-16T08:30:00'),
            notes: 'Automated alert generated by AI system'
          }
        ]
      },
      {
        id: 'ALT-2025-002',
        timestamp: new Date('2025-01-16T07:15:00'),
        location: 'South Pit - Zone C',
        severity: 'High',
        riskType: 'Slope Instability',
        status: 'Acknowledged',
        description: `High risk slope instability detected in South Pit Zone C. Monitoring sensors show increased displacement rates and stress patterns indicating potential slope failure.\n\nRecommended actions include restricting access and increasing monitoring frequency.`,
        riskProbability: 78,
        confidenceLevel: 82,
        affectedArea: '300m x 150m',
        sensorSource: 'Geotechnical Array SP-C-03',
        weather: 'Overcast',
        temperature: '15°C',
        windSpeed: '12 km/h',
        rainfall: '5mm/24h',
        coordinates: { lat: -33.8700, lng: 151.2080 },
        responseHistory: [
          {
            user: 'Mike Chen',
            action: 'Alert Acknowledged',
            timestamp: new Date('2025-01-16T07:45:00'),
            notes: 'Safety team notified, area access restricted'
          }
        ]
      },
      {
        id: 'ALT-2025-003',
        timestamp: new Date('2025-01-16T06:45:00'),
        location: 'East Slope - Sector 1',
        severity: 'Medium',
        riskType: 'Ground Movement',
        status: 'Investigating',
        description: `Medium risk ground movement detected in East Slope Sector 1. Gradual displacement patterns observed over past 48 hours with accelerating trend.\n\nGeotechnical team investigating root cause and assessing long-term stability.`,
        riskProbability: 65,
        confidenceLevel: 75,
        affectedArea: '100m x 100m',
        sensorSource: 'Displacement Monitor ES-S1-02',
        weather: 'Clear',
        temperature: '18°C',
        windSpeed: '8 km/h',
        rainfall: '0mm/24h',
        coordinates: { lat: -33.8675, lng: 151.2110 },
        responseHistory: [
          {
            user: 'Dr. Emily Rodriguez',
            action: 'Investigation Started',
            timestamp: new Date('2025-01-16T07:00:00'),
            notes: 'Geotechnical team deployed for detailed assessment'
          }
        ]
      },
      {
        id: 'ALT-2025-004',
        timestamp: new Date('2025-01-16T05:30:00'),
        location: 'West Slope - Sector 2',
        severity: 'Low',
        riskType: 'Environmental',
        status: 'Resolved',
        description: `Low risk environmental alert for West Slope Sector 2. Elevated dust levels detected due to increased wind activity.\n\nDust suppression systems activated and levels returned to normal parameters.`,
        riskProbability: 25,
        confidenceLevel: 90,
        affectedArea: '50m x 75m',
        sensorSource: 'Environmental Monitor WS-S2-01',
        weather: 'Windy',
        temperature: '20°C',
        windSpeed: '35 km/h',
        rainfall: '0mm/24h',
        coordinates: { lat: -33.8650, lng: 151.2050 },
        responseHistory: [
          {
            user: 'James Wilson',
            action: 'Dust Suppression Activated',
            timestamp: new Date('2025-01-16T05:45:00'),
            notes: 'Automatic dust suppression system engaged'
          },
          {
            user: 'James Wilson',
            action: 'Alert Resolved',
            timestamp: new Date('2025-01-16T06:15:00'),
            notes: 'Dust levels returned to normal, alert resolved'
          }
        ]
      },
      {
        id: 'ALT-2025-005',
        timestamp: new Date('2025-01-16T04:20:00'),
        location: 'North Pit - Zone B',
        severity: 'High',
        riskType: 'Structural Failure',
        status: 'Active',
        description: `High risk structural failure detected in North Pit Zone B. Support structure showing signs of stress and potential failure.\n\nImmediate inspection and reinforcement required to prevent catastrophic failure.`,
        riskProbability: 82,
        confidenceLevel: 88,
        affectedArea: '200m x 100m',
        sensorSource: 'Structural Monitor NP-B-04',
        weather: 'Light Rain',
        temperature: '14°C',
        windSpeed: '18 km/h',
        rainfall: '12mm/24h',
        coordinates: { lat: -33.8695, lng: 151.2100 },
        responseHistory: []
      },
      {
        id: 'ALT-2025-006',
        timestamp: new Date('2025-01-15T23:45:00'),
        location: 'Central Processing Area',
        severity: 'Medium',
        riskType: 'Ground Movement',
        status: 'Acknowledged',
        description: `Medium risk ground movement detected near Central Processing Area. Subsidence patterns indicate potential underground void formation.\n\nGeophysical survey recommended to assess extent of underground changes.`,
        riskProbability: 58,
        confidenceLevel: 72,
        affectedArea: '80m x 120m',
        sensorSource: 'Ground Monitor CPA-01',
        weather: 'Clear',
        temperature: '16°C',
        windSpeed: '10 km/h',
        rainfall: '2mm/24h',
        coordinates: { lat: -33.8680, lng: 151.2085 },
        responseHistory: [
          {
            user: 'Lisa Thompson',
            action: 'Alert Acknowledged',
            timestamp: new Date('2025-01-16T00:15:00'),
            notes: 'Night shift supervisor notified, area marked for morning inspection'
          }
        ]
      }
    ];

    setAlerts(mockAlerts);
    setFilteredAlerts(mockAlerts);
  }, []);

  // Filter alerts based on current filters
  useEffect(() => {
    let filtered = [...alerts];

    if (filters?.severity) {
      filtered = filtered?.filter(alert => alert?.severity === filters?.severity);
    }
    if (filters?.location) {
      filtered = filtered?.filter(alert => alert?.location === filters?.location);
    }
    if (filters?.status) {
      filtered = filtered?.filter(alert => alert?.status === filters?.status);
    }
    if (filters?.riskType) {
      filtered = filtered?.filter(alert => alert?.riskType === filters?.riskType);
    }
    if (filters?.startDate) {
      filtered = filtered?.filter(alert => 
        new Date(alert.timestamp) >= new Date(filters.startDate)
      );
    }
    if (filters?.endDate) {
      filtered = filtered?.filter(alert => 
        new Date(alert.timestamp) <= new Date(filters.endDate + 'T23:59:59')
      );
    }

    setFilteredAlerts(filtered);
    setSelectedAlerts([]);
  }, [filters, alerts]);

  // Calculate alert counts for filter options
  const alertCounts = useMemo(() => {
    const counts = {
      Critical: 0,
      High: 0,
      Medium: 0,
      Low: 0,
      Active: 0,
      Acknowledged: 0,
      Investigating: 0,
      Resolved: 0,
      locations: {},
      riskTypes: {}
    };

    alerts?.forEach(alert => {
      counts[alert.severity] = (counts?.[alert?.severity] || 0) + 1;
      counts[alert.status] = (counts?.[alert?.status] || 0) + 1;
      counts.locations[alert.location] = (counts?.locations?.[alert?.location] || 0) + 1;
      counts.riskTypes[alert.riskType] = (counts?.riskTypes?.[alert?.riskType] || 0) + 1;
    });

    return counts;
  }, [alerts]);

  const handleFilterChange = (key, value) => {
    setFilters(prev => ({
      ...prev,
      [key]: value
    }));
  };

  const handleClearFilters = () => {
    setFilters({
      severity: '',
      location: '',
      status: '',
      riskType: '',
      startDate: '',
      endDate: ''
    });
  };

  const handleSelectAlert = (alertId, isSelected) => {
    setSelectedAlerts(prev => 
      isSelected 
        ? [...prev, alertId]
        : prev?.filter(id => id !== alertId)
    );
  };

  const handleSelectAll = (isSelected) => {
    setSelectedAlerts(isSelected ? filteredAlerts?.map(alert => alert?.id) : []);
  };

  const handleAcknowledge = (alertId) => {
    setAlerts(prev => prev?.map(alert => 
      alert?.id === alertId 
        ? { 
            ...alert, 
            status: 'Acknowledged',
            responseHistory: [
              ...alert?.responseHistory,
              {
                user: 'Current User',
                action: 'Alert Acknowledged',
                timestamp: new Date(),
                notes: 'Alert acknowledged by user'
              }
            ]
          }
        : alert
    ));
  };

  const handleEscalate = (alertId) => {
    setAlerts(prev => prev?.map(alert => 
      alert?.id === alertId 
        ? { 
            ...alert, 
            responseHistory: [
              ...alert?.responseHistory,
              {
                user: 'Current User',
                action: 'Alert Escalated',
                timestamp: new Date(),
                notes: 'Alert escalated to next level'
              }
            ]
          }
        : alert
    ));
  };

  const handleViewDetails = (alert) => {
    setSelectedAlert(alert);
    setIsDetailsOpen(true);
  };

  const handleBulkAction = async (action, alertIds) => {
    switch (action) {
      case 'acknowledge':
        alertIds?.forEach(id => handleAcknowledge(id));
        break;
      case 'escalate':
        alertIds?.forEach(id => handleEscalate(id));
        break;
      case 'resolve':
        setAlerts(prev => prev?.map(alert => 
          alertIds?.includes(alert?.id) 
            ? { 
                ...alert, 
                status: 'Resolved',
                responseHistory: [
                  ...alert?.responseHistory,
                  {
                    user: 'Current User',
                    action: 'Alert Resolved',
                    timestamp: new Date(),
                    notes: 'Alert marked as resolved via bulk action'
                  }
                ]
              }
            : alert
        ));
        break;
      case 'export':
        // Mock export functionality
        const exportData = alerts?.filter(alert => alertIds?.includes(alert?.id));
        console.log('Exporting alerts:', exportData);
        alert('Export completed successfully!');
        break;
      default:
        break;
    }
    setSelectedAlerts([]);
  };

  const handleSaveConfiguration = (config) => {
    console.log('Saving configuration:', config);
    // Mock save functionality
    alert('Configuration saved successfully!');
  };

  const activeAlertCount = alerts?.filter(alert => alert?.status === 'Active')?.length;

  return (
    <div className="min-h-screen bg-background">
      <Header 
        currentSite={currentSite}
        onSiteChange={setCurrentSite}
        alertCount={activeAlertCount}
      />
      <main className="pt-16">
        <div className="max-w-7xl mx-auto px-6 py-8">
          <Breadcrumb />
          
          {/* Page Header */}
          <div className="flex items-center justify-between mb-8">
            <div>
              <h1 className="text-3xl font-bold text-foreground mb-2">Alert Management</h1>
              <p className="text-muted-foreground">
                Monitor and respond to rockfall risk notifications across all mine sites
              </p>
            </div>
            <div className="flex items-center space-x-3">
              <Button
                variant="outline"
                onClick={() => setIsConfigOpen(true)}
                iconName="Settings"
                iconSize={16}
              >
                Configuration
              </Button>
              <Link to="/site-risk-analysis">
                <Button
                  variant="secondary"
                  iconName="TrendingUp"
                  iconSize={16}
                >
                  Risk Analysis
                </Button>
              </Link>
            </div>
          </div>

          {/* Alert Statistics */}
          <AlertStats alerts={alerts} />

          {/* Alert Filters */}
          <AlertFilters
            filters={filters}
            onFilterChange={handleFilterChange}
            onClearFilters={handleClearFilters}
            alertCounts={alertCounts}
          />

          {/* Bulk Actions */}
          <BulkActions
            selectedAlerts={selectedAlerts}
            onBulkAction={handleBulkAction}
            onClearSelection={() => setSelectedAlerts([])}
          />

          {/* Results Summary */}
          <div className="flex items-center justify-between mb-4">
            <div className="flex items-center space-x-4">
              <span className="text-sm text-muted-foreground">
                Showing {filteredAlerts?.length} of {alerts?.length} alerts
              </span>
              {filteredAlerts?.length !== alerts?.length && (
                <span className="text-sm text-primary">
                  (Filtered)
                </span>
              )}
            </div>
            <div className="flex items-center space-x-2">
              <Icon name="Clock" size={16} className="text-muted-foreground" />
              <span className="text-sm text-muted-foreground">
                Last updated: {new Date()?.toLocaleTimeString()}
              </span>
            </div>
          </div>

          {/* Alert Table */}
          <AlertTable
            alerts={filteredAlerts}
            onAcknowledge={handleAcknowledge}
            onEscalate={handleEscalate}
            onViewDetails={handleViewDetails}
            selectedAlerts={selectedAlerts}
            onSelectAlert={handleSelectAlert}
            onSelectAll={handleSelectAll}
          />

          {/* Empty State */}
          {filteredAlerts?.length === 0 && alerts?.length > 0 && (
            <div className="text-center py-12">
              <Icon name="Search" size={48} className="text-muted-foreground mx-auto mb-4" />
              <h3 className="text-lg font-medium text-foreground mb-2">No alerts match your filters</h3>
              <p className="text-muted-foreground mb-4">
                Try adjusting your filter criteria to see more results.
              </p>
              <Button variant="outline" onClick={handleClearFilters}>
                Clear All Filters
              </Button>
            </div>
          )}
        </div>
      </main>
      {/* Alert Configuration Modal */}
      <AlertConfiguration
        isOpen={isConfigOpen}
        onClose={() => setIsConfigOpen(false)}
        onSave={handleSaveConfiguration}
      />
      {/* Alert Details Modal */}
      <AlertDetails
        alert={selectedAlert}
        isOpen={isDetailsOpen}
        onClose={() => {
          setIsDetailsOpen(false);
          setSelectedAlert(null);
        }}
        onAcknowledge={handleAcknowledge}
        onEscalate={handleEscalate}
      />
    </div>
  );
};

export default AlertManagement;